location1 = Location.create(name: "Tech")
location2 = Location.create(name: "Finanzas")
Worker.create(name: 'Jose', location_id: location1.id)
Worker.create(name: 'Amy', location_id: location2.id)
Worker.create(name: 'Dani', location_id: location2.id)
